version: '3.4'

services:
  ataskapi:
    image: ${DOCKER_REGISTRY-}ataskapi
    build:
      context: .
      dockerfile: ATaskApi/Dockerfile
    environment:
      - CONTAINER_NAME=ataskapi-container
      

  

