version: '3.4'

services:
  ataskapi:
    image: ${DOCKER_REGISTRY-}ataskapi
    build:
      context: .
      dockerfile: ATaskApi/Dockerfile
    environment:
      - CONTAINER_NAME=ataskapi-container
      - JENKINS_PORT=8081

  #unittestproject1:
  #  image: ${DOCKER_REGISTRY-}unittestproject1
  #  build:
  #    context: .
  #    dockerfile: UnitTestProject1/Dockerfile

